#!/usr/bin/env ruby

# Bundler/Gemfile is not necessary to use ginjo-rfm gem.
# It is only here for development & testing.
# See http://bundler.io/man/gemfile.5.html for more info.

source 'https://rubygems.org'
gemspec

# TODO: Remove this before shipping.
gem 'rfm-sax', path:'/Users/wbr/Documents/Programming/GitProjects/GinjoRfm.git/sax'

# If you don't want dev dependencies.
# bundle install --without development

# Required for ruby < 2.2
#gem 'activesupport', "< 4"
#gem 'rdoc', "< 6"

